name: GoTestingREST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.23'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        folder: [ "api", "bdd", "perfomance" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests and generate JUnit report
        run: |
          go install gotest.tools/gotestsum@latest
          gotestsum --junitfile report-${{ matrix.folder }}.xml --format short-verbose ${{ matrix.folder }}

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.folder }}
          path: report-${{ matrix.folder }}.xml

      - name: Publish test results to GitHub
        uses: dorny/test-reporter@v1
        with:
          name: Go Tests ${{ matrix.folder }}
          path: report-${{ matrix.folder }}.xml
          reporter: go-test