name: GoTesting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.23'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [ "api", "bdd" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          
      - name: Build
        run: |
          cd ./${{ matrix.folder }}
          go build -v

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        folder: [ "api", "bdd" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Tests for Module [${{ matrix.folder }}]
        run: |
          cd ./${{ matrix.folder }}/tests
          go test -v