name: GoTestingREST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.23'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: go build -v ./api

#      - name: Build
#        run: go build -v ./../bdd

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        folder: [ "api", "bdd" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Tests for Module api
        run: |
          cd ./api/tests
          go test ./api/tests

#      - name: Run Tests for Module bdd
#        run: |
#          cd ./../api/tests
#          go test ./../bdd/tests