name: GoTesting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.23'
  ACTIONS: 'actions/setup-go@v5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: ${{ env.ACTIONS }}
        with:
          go-version: ${{ env.GO_VERSION }}

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        folder: [ "api", "bdd" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: ${{ env.ACTIONS }}
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Tests for Module ${{ matrix.folder }}
        run: |
          cd ./${{ matrix.folder }}/tests
          go test